version: "3.8"

services:
  redis:
    image: redislabs/redisearch:latest
    ports:
      - "16379:6379"
    volumes:
      - $PWD/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --dir /data --loadmodule /usr/lib/redis/modules/redisearch.so MINPREFIX 1

  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/redis-sitesearch
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: ./
      dockerfile: docker/worker/Dockerfile
    volumes:
      - $PWD:/redis-sitesearch
    env_file:
      - .env
    depends_on:
      - redis

  scheduler:
    build:
      context: ./
      dockerfile: docker/scheduler/Dockerfile
    volumes:
      - $PWD:/redis-sitesearch
    env_file:
      - .env
    depends_on:
      - redis

  test:
    build:
      context: ./
      dockerfile: docker/test/Dockerfile
    entrypoint: "pytest -s"
    volumes:
      - $PWD:/redis-sitesearch
    env_file:
      - .env
    depends_on:
        - redis
