version: "3.8"

services:
  app:
    build: .
    ports:
      - "6379:6379"
      - "8080:8080"
    volumes:
      - $PWD/data:/data
      - $PWD:/src
    env_file:
      - .env

  test:
    build: .
    entrypoint: "/src/test.sh"
    volumes:
      - $PWD:/src
    env_file:
      - .env.test
